repos:
  - repo: https://github.com/errata-ai/vale
    rev: v3.7.1
    hooks:
      - id: vale
        verbose: true
        # Always exit successfully, never block
        pass_filenames: true
        args: ['--config=.vale.ini']
        always_run: false
        # Override to never fail
        stages: [manual]