repos:
  - repo: local
    hooks:
      - id: vale
        name: vale
        entry: bash -c 'vale --config=.vale.ini "$@"; exit 0' --
        language: system
        files: \.(md|mdx)$
        exclude: 'changelog/'
        pass_filenames: true
        verbose: true
