StylesPath = .vale/styles

MinAlertLevel = suggestion

Packages = Microsoft

[formats]
mdx = md

[*.mdx]
BasedOnStyles = Microsoft, FernStyles

# Disable specific rules
# Not relevant for technical documentation
Microsoft.GenderBias = NO

# Too granular
Microsoft.Accessibility = NO
Microsoft.Passive = NO
Microsoft.Suspended = NO
Microsoft.Vocab = NO
Microsoft.Spacing = NO
Microsoft.Semicolon = NO # Mostly just picks up code
Microsoft.SentenceLength = NO # Mostly just picks up code
Microsoft.Ellipses = NO # Mostly just picks up code
Microsoft.Dashes = NO
Microsoft.Foreign = NO
Microsoft.Plurals = NO
Microsoft.Quotes = NO # Mostly just picks up code
Microsoft.Auto = NO

# Not relevant for Fern audience
Microsoft.GeneralURL = NO
Microsoft.HeadingAcronyms = NO
Microsoft.Terms = NO

# Handled in FernStyles
Microsoft.Acronyms = NO
Microsoft.Adverbs = NO
Microsoft.Ellipses = NO
Microsoft.FirstPerson = NO
Microsoft.Headings = NO
Microsoft.HeadingPunctuation = NO
Microsoft.Hyphens = NO
Microsoft.We = NO
Microsoft.Avoid = NO

# Changelog entries use time-relative terms ("You can now...") by convention
[**/changelog/*.mdx]
FernStyles.Current = NO

