StylesPath = .vale/styles

MinAlertLevel = suggestion

Packages = Microsoft

[formats]
mdx = md

[*.mdx]
BasedOnStyles = Microsoft, FernStyles

# Disable specific rules
Microsoft.GenderBias = NO # Not relevant for technical documentation
Microsoft.Acronyms = NO # Handled in FernStyles
Microsoft.Vocab = NO # Too granular for now
Microsoft.HeadingAcronyms = NO # Not relevant for Fern audience
Microsoft.GeneralURL = NO # Not relevant for Fern audience
Microsoft.Passive = NO # Too noisy
Microsoft.Accessibility = NO # Too noisy


