StylesPath = .vale/styles

MinAlertLevel = suggestion

Packages = Microsoft

[*.mdx]
BasedOnStyles = Microsoft, FernStyles

# Disable specific rules
Microsoft.GenderBias = NO # Not relevant for technical documentation

