name: Run Vale linter
on: 
  pull_request:
    paths:
      - '**.mdx'
      - '**.md'
      - '.vale/**'
      - '.vale.ini'

jobs:
  vale:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login != 'fern-support' &&
      github.event.pull_request.user.login != 'github-actions'
    steps:
      - uses: actions/checkout@v4
      
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: fern
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}