name: Vale style check
on: 
  pull_request:
    paths:
      - '**.mdx'
      - '**.md'
      - '.vale/**'
      - '.vale.ini'
      - '!**/changelog/**'

jobs:
  vale:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login != 'fern-support' &&
      github.event.pull_request.user.login != 'github-actions'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            fern/**/*.md
            fern/**/*.mdx
          files_ignore: |
            **/changelog/**
      - uses: errata-ai/vale-action@d89dee975228ae261d22c15adcd03578634d429c # v2.1.1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          version: 3.12.0
          reporter: github-pr-review
          fail_on_error: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
